# Generated by Django 5.0 on 2024-01-27 18:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("base", "0011_diva_college_hunk_college"),
    ]

    operations = [
        migrations.AlterField(
            model_name="voter",
            name="otp",
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
    ]
