# Generated by Django 5.0 on 2024-02-06 21:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("base", "0012_alter_voter_otp"),
    ]

    operations = [
        migrations.AddField(
            model_name="voter",
            name="otp_timestamp",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
