# Generated by Django 5.0 on 2024-03-02 14:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("base", "0013_voter_otp_timestamp"),
    ]

    operations = [
        migrations.AddField(
            model_name="diva",
            name="image1",
            field=models.ImageField(default="user.png", upload_to="images/"),
        ),
        migrations.AddField(
            model_name="diva",
            name="image2",
            field=models.ImageField(default="user.png", upload_to="images/"),
        ),
    ]
