# Generated by Django 5.0 on 2024-03-02 14:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("base", "0014_diva_image1_diva_image2"),
    ]

    operations = [
        migrations.AddField(
            model_name="hunk",
            name="image1",
            field=models.ImageField(default="user.png", upload_to="images/"),
        ),
        migrations.AddField(
            model_name="hunk",
            name="image2",
            field=models.ImageField(default="user.png", upload_to="images/"),
        ),
    ]
